from setuptools import setup, find_packages

setup(
    name="ultimate-test-automation",
    version="1.0.0",
    description="Ultimate AI Test Automation Coordinator",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "crewai==0.28.8",
        "crewai-tools==0.1.6",
        "google-generativeai==0.3.2",
        "jira==3.6.0",
        "pytest==7.4.3",
        "playwright==1.39.0",
        "pytest-html==4.0.2",
        "requests==2.31.0",
        "faker==19.6.2",
        "pyyaml==6.0.1",
        "pytest-xvfb==2.0.0",
        "selenium==4.15.0",
        "webdriver-manager==4.0.1",
        "beautifulsoup4==4.12.2",
        "aiohttp==3.9.1",
        "asyncio-throttle==1.0.2",
        "pandas==2.1.1",
        "numpy==1.25.2",
        "matplotlib==3.7.2",
        "seaborn==0.12.2",
        "plotly==5.17.0",
        "dash==2.14.1",
        "redis==5.0.1",
        "celery==5.3.4",
        "kombu==5.3.4",
        "prometheus-client==0.18.0",
        "tenacity==8.2.3",
        "backoff==2.2.1",
        "pybreaker==0.8.0",
        "memory-profiler==0.61.0",
        "psutil==5.9.6",
        "gputil==1.4.0",
        "py-cpuinfo==9.0.0",
    ],
    entry_points={
        "console_scripts": [
            "test-automation=run:main",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Quality Engineers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
)