execution:
  mode: adaptive
  max_parallel_tests: 8
  timeout_base: 30
  timeout_multiplier: 1.5
  adaptive_scaling: true
  resource_monitoring: true

retry_policy:
  max_attempts: 5
  backoff_factor: 2.0
  backoff_max: 300
  exponential_base: 2
  jitter: true
  circuit_breaker_threshold: 0.5

performance:
  memory_limit_mb: 2048
  cpu_limit_percent: 80
  enable_profiling: true
  metrics_collection: true
  auto_optimization: true

security:
  encrypt_sensitive_data: true
  audit_logging: true
  rate_limiting: true
  input_validation: true

ai_features:
  intelligent_test_generation: true
  self_healing_tests: true
  predictive_failure_analysis: true
  automatic_optimization: true

integrations:
  jira_advanced_features: true
  slack_rich_notifications: true
  prometheus_metrics: true
  grafana_dashboards: true

test_scenarios:
  login_form:
    selectors:
      - input[name="username"]
      - input[name="email"]
      - input[type="email"]
      - "#email"
      - "#username"
    password_selectors:
      - input[name="password"]
      - input[type="password"]
      - "#password"
    submit_selectors:
      - button[type="submit"]
      - input[type="submit"]
      - ".login-btn"
      - ".submit-btn"
      - "#login"
    success_indicators:
      - dashboard
      - welcome
      - profile
      - logout
      - account
      - home
    failure_indicators:
      - error
      - invalid
      - incorrect
      - failed
      - denied

  contact_form:
    selectors:
      - input[name="name"]
      - "#contact-name"
      - ".name-field"
      - "#name"
    email_selectors:
      - input[name="email"]
      - input[type="email"]
      - "#email"
    message_selectors:
      - textarea[name="message"]
      - "#message"
      - ".message-field"
      - "#contact-message"
    submit_selectors:
      - button[type="submit"]
      - ".submit-btn"
      - "#submit"
      - ".contact-submit"
    success_indicators:
      - thank you
      - message sent
      - success
      - received
      - contact received
    failure_indicators:
      - error
      - failed
      - invalid
      - required

  registration_form:
    selectors:
      - input[name="username"]
      - input[name="firstname"]
      - "#username"
      - "#firstname"
    email_selectors:
      - input[name="email"]
      - input[type="email"]
      - "#email"
    password_selectors:
      - input[name="password"]
      - "#password"
    confirm_password_selectors:
      - input[name="confirm_password"]
      - input[name="password_confirmation"]
      - "#confirm_password"
    submit_selectors:
      - button[type="submit"]
      - ".register-btn"
      - "#register"
      - ".signup-btn"
    success_indicators:
      - registration successful
      - account created
      - welcome
      - verify email
    failure_indicators:
      - error
      - exists
      - invalid
      - weak password

  search_form:
    query_selectors:
      - input[name="q"]
      - input[name="query"]
      - input[name="search"]
      - "#search"
      - ".search-input"
    submit_selectors:
      - button[type="submit"]
      - ".search-btn"
      - "#search-btn"
    success_indicators:
      - results
      - found
      - matches
      - search results
    failure_indicators:
      - no results
      - not found
      - error