# Feature: HMHEPS-472 - TC-001: Verify Welcome Screen for Admin with Rostering Rights on First Login
# Generated by Ultimate Test Automation Coordinator

Feature: Test cases for JIRA ticket HMHEPS-472


Scenario: TC-001: Verify Welcome Screen for Admin with Rostering Rights on First Login
    Description: This test case validates the complete happy path for an Ed administrator with rostering rights logging in for the very first time, including the welcome message, transition, and navigation to 'Configure Settings'.
    Priority: High
    Type: Positive

    Given As a test administrator, ensure the target user has never logged into the platform before.
    Given Log in as the Ed administrator with rostering rights.
    Given Observe the initial welcome message.
    Given Wait for the screen to transition automatically.
    Given On the 'Let's Get Started' screen, click the 'Configure Settings' button.
    Then The user should first see a 'Welcome {Name}' message for approximately 1000ms. The screen should then transition to the 'Let's Get Started' view. Upon clicking 'Configure Settings', the user must be redirected to the 'My schools → Roster' page.

Scenario: TC-002: Verify One-Time Display Logic after Clicking 'Go to Home'
    Description: This test case ensures that the welcome screen is only shown once. It verifies that after completing the flow by clicking 'Go to Home' and logging in again, the user is taken directly to the home page.
    Priority: High
    Type: Positive

    Given Log in as a new Ed administrator with rostering rights.
    Given On the 'Let's Get Started' screen, click the 'Go to Home' button.
    Given Verify you are on the standard Home page.
    Given Log out of the application.
    Given Log back in using the same administrator credentials.
    Then On the first login, the welcome flow is presented and clicking 'Go to Home' navigates to the Home page. On the second login, the welcome screen is skipped entirely, and the user lands directly on the Home page.

Scenario: TC-003: Verify Admin without Rostering Rights Bypasses the Welcome Screen
    Description: This is a negative test case to confirm that an administrator who lacks rostering rights is never shown the welcome screen and is immediately directed to their home page upon login.
    Priority: High
    Type: Negative

    Given Log in as an Ed administrator who does NOT have rostering rights.
    Then The user should be immediately redirected to the standard Home page. The 'Welcome {Name}' message and the 'Let's Get Started' screen should not be displayed at any point.

Scenario: TC-004: Verify UI Elements and Timing of the Welcome Screen
    Description: This test case focuses on the user interface and experience, verifying the content, presence of elements, and the specified timing of the initial welcome animation.
    Priority: Medium
    Type: Basic Functionality

    Given Log in as a new Ed administrator with rostering rights.
    Given Observe the initial screen and use a timer or browser dev tools to check the duration.
    Given Once the screen transitions, inspect the text of the two available buttons.
    Then A message 'Welcome {Correct User Name}' is displayed. This message is visible for approximately 1000ms. It is then replaced by the 'Let's Get Started' screen, which contains two distinct buttons labeled 'Go to Home' and 'Configure Settings'.

Scenario: TC-005: Verify Behavior when Feature Flag is Disabled
    Description: This test case ensures that the entire feature is correctly hidden behind its feature flag. When the flag is off, no user should experience the new welcome flow.
    Priority: High
    Type: Negative

    Given Ensure the 'Welcome Screen' Feature Flag is turned OFF in the environment configuration.
    Given Log in as a new Ed administrator WITH rostering rights.
    Given Observe the landing page.
    Given Log out and log in as an Ed administrator WITHOUT rostering rights.
    Given Observe the landing page.
    Then For both user types (with and without rostering rights), the welcome screen flow is completely bypassed. Both users should land directly on the standard Home page.

Scenario: TC-006: Verify Behavior on Browser Refresh on the 'Let's Get Started' Screen
    Description: This edge case checks the state persistence of the welcome flow. If a user refreshes the page on the choice screen, they should not be prematurely exited from the flow.
    Priority: Medium
    Type: Edge Case

    Given Log in as a new Ed administrator with rostering rights.
    Given Wait for the screen to transition to the 'Let's Get Started' view.
    Given Instead of clicking a button, refresh the browser page (e.g., using F5 or the refresh icon).
    Then After the page reloads, the user should be presented with the 'Let's Get Started' screen again. The one-time welcome flow should not be considered complete, and the user should not be redirected to the home page.
