# Feature: KAN-2 - Test creating a new class
# Generated by Ultimate Test Automation Coordinator

Feature: Test cases for JIRA ticket KAN-2


Scenario: Test creating a new class
    Description: Verify ability to create a new class with valid parameters
    Priority: High
    Type: Functional

    Given Navigate to class management section
    Given Click 'Create New Class' button
    Given Enter valid class name and details
    Given Save the class
    Then New class is created successfully and appears in class list

Scenario: Test adding student to class
    Description: Verify ability to add a student to an existing class
    Priority: High
    Type: Functional

    Given Navigate to class management section
    Given Select an existing class
    Given Click 'Add Student' button
    Given Enter valid student information
    Given Save student details
    Then Student is added to the class successfully

Scenario: Test duplicate class creation
    Description: Verify system prevents creating duplicate classes
    Priority: Medium
    Type: Negative

    Given Navigate to class management section
    Given Click 'Create New Class' button
    Given Enter class name that already exists
    Given Save the class
    Then System displays error message about duplicate class

Scenario: Test adding student with invalid data
    Description: Verify system validates student information properly
    Priority: Medium
    Type: Negative

    Given Navigate to class management section
    Given Select an existing class
    Given Click 'Add Student' button
    Given Enter invalid student information
    Given Save student details
    Then System displays validation errors and prevents saving

Scenario: Test class list display
    Description: Verify classes are displayed correctly in the list
    Priority: Low
    Type: UI

    Given Navigate to class management section
    Given View the list of classes
    Then All existing classes are displayed with correct information
