# Feature: KAN-2 - TC_KAN_2_01_Positive_ClassCreation
# Generated by Ultimate Test Automation Coordinator

Feature: Test cases for JIRA ticket KAN-2


Scenario: TC_KAN_2_01_Positive_ClassCreation
    Description: Verify successful creation of a new class with valid data.
    Priority: High
    Type: Positive

    Given Login as teacher 'Auksh123' with password 'Pass@123'
    Given Navigate to 'Manage Rosters'
    Given Click on 'Create Class'
    Given Enter valid class name and other required details
    Given Click 'Create'
    Given Verify class is created successfully and displayed in the class list
    Then A new class is successfully created and displayed in the class list.

Scenario: TC_KAN_2_02_Positive_StudentCreation
    Description: Verify successful creation and addition of a new student to a class.
    Priority: High
    Type: Positive

    Given Login as teacher 'Auksh123' with password 'Pass@123'
    Given Navigate to 'Manage Rosters'
    Given Select the newly created class 'Test Class 1'
    Given Click on 'Add Students'
    Given Enter valid student details (name, ID, etc.)
    Given Click 'Add'
    Given Verify student is added to the class roster
    Then A new student is successfully added to the class roster.

Scenario: TC_KAN_2_03_Negative_InvalidClassName
    Description: Verify error handling when creating a class with an invalid class name (e.g., empty or special characters).
    Priority: Medium
    Type: Negative

    Given Login as teacher 'Auksh123' with password 'Pass@123'
    Given Navigate to 'Manage Rosters'
    Given Click on 'Create Class'
    Given Enter an invalid class name (e.g., empty or containing special characters)
    Given Click 'Create'
    Then An appropriate error message is displayed, preventing class creation.

Scenario: TC_KAN_2_04_Negative_InvalidStudentData
    Description: Verify error handling when adding a student with invalid data (e.g., empty fields).
    Priority: Medium
    Type: Negative

    Given Login as teacher 'Auksh123' with password 'Pass@123'
    Given Navigate to 'Manage Rosters'
    Given Select the newly created class 'Test Class 1'
    Given Click on 'Add Students'
    Given Enter invalid student details (e.g., empty name field)
    Given Click 'Add'
    Then An appropriate error message is displayed, preventing student addition.

Scenario: TC_KAN_2_05_Edge_MaxCharacters
    Description: Verify system behavior when creating a class with a class name containing the maximum allowed number of characters.
    Priority: Low
    Type: Edge

    Given Login as teacher 'Auksh123' with password 'Pass@123'
    Given Navigate to 'Manage Rosters'
    Given Click on 'Create Class'
    Given Enter a class name with the maximum allowed number of characters
    Given Click 'Create'
    Then The class is created successfully.

Scenario: TC_KAN_2_06_Basic_Navigation
    Description: Verify navigation between different sections after class and student creation.
    Priority: Medium
    Type: Basic Functionality

    Given Follow steps from TC_KAN_2_01 and TC_KAN_2_02
    Given Navigate to 'Home'
    Given Verify that the newly created class is visible on the home page
    Given Navigate to the newly created class
    Then Successful navigation to home page and back to the newly created class
