# Feature: KAN-1 - TC001_Login_Successful_Valid_Credentials
# Generated by Ultimate Test Automation Coordinator

Feature: Test cases for JIRA ticket KAN-1


Scenario: TC001_Login_Successful_Valid_Credentials
    Description: Verify user can successfully log in with a valid username and password.
    Priority: High
    Type: Positive

    Given Navigate to the HMH Ed login page.
    Given Enter a valid, registered username in the username field.
    Given Enter the corresponding correct password in the password field.
    Given Click the 'Sign In' or 'Login' button.
    Then User is authenticated and redirected to the application's main dashboard or home page.

Scenario: TC002_Login_Failed_Invalid_Password
    Description: Verify user cannot log in with a valid username but an incorrect password.
    Priority: High
    Type: Negative

    Given Navigate to the HMH Ed login page.
    Given Enter a valid, registered username.
    Given Enter an incorrect password.
    Given Click the 'Sign In' or 'Login' button.
    Then An appropriate error message (e.g., 'Invalid username or password.') is displayed. The user remains on the login page.

Scenario: TC003_Login_Failed_Invalid_Username
    Description: Verify user cannot log in with a non-existent username.
    Priority: High
    Type: Negative

    Given Navigate to the HMH Ed login page.
    Given Enter a username that is not registered in the system.
    Given Enter any password.
    Given Click the 'Sign In' or 'Login' button.
    Then A generic error message (e.g., 'Invalid username or password.') is displayed to prevent user enumeration. The user remains on the login page.

Scenario: TC004_Login_Failed_Empty_Credentials
    Description: Verify system behavior when the user attempts to log in with empty username and password fields.
    Priority: Medium
    Type: Negative

    Given Navigate to the HMH Ed login page.
    Given Leave the username field blank.
    Given Leave the password field blank.
    Given Click the 'Sign In' or 'Login' button.
    Then Client-side validation errors appear, prompting the user to enter a username and password (e.g., 'This field is required'). The login request is not sent to the server.

Scenario: TC005_Login_Username_Case_Insensitivity
    Description: Verify that the username field is not case-sensitive.
    Priority: Medium
    Type: Edge Case

    Given Navigate to the HMH Ed login page.
    Given Enter a valid username but in a different letter case (e.g., uppercase or mixed case).
    Given Enter the corresponding correct password.
    Given Click the 'Sign In' or 'Login' button.
    Then User is successfully authenticated and redirected to the dashboard, confirming the username is case-insensitive.

Scenario: TC006_Login_Password_Case_Sensitivity
    Description: Verify that the password field is case-sensitive for security.
    Priority: High
    Type: Edge Case

    Given Navigate to the HMH Ed login page.
    Given Enter a valid username.
    Given Enter the correct password but with incorrect letter casing.
    Given Click the 'Sign In' or 'Login' button.
    Then Login fails and an 'Invalid username or password.' error is displayed, confirming the password field is case-sensitive.

Scenario: TC007_Login_Password_Field_Masking
    Description: Verify that text entered into the password field is masked.
    Priority: Medium
    Type: Basic Functionality

    Given Navigate to the HMH Ed login page.
    Given Click on the password field.
    Given Type a sequence of characters into the password field.
    Then The characters entered in the password field are obscured (e.g., displayed as dots or asterisks) and not shown in plain text.

Scenario: TC008_Login_Forgot_Password_Link_Functionality
    Description: Verify the 'Forgot Password?' or 'Need help?' link is present and functional.
    Priority: Medium
    Type: Basic Functionality

    Given Navigate to the HMH Ed login page.
    Given Locate and click on the 'Forgot Password?' link.
    Then The user is successfully redirected to the password recovery page or modal.
