# Feature: KAN-2 - TC_GETSCORE_01: Retrieve score for a valid student and assessment
# Generated by Ultimate Test Automation Coordinator

Feature: Test cases for JIRA ticket KAN-2


Scenario: TC_GETSCORE_01: Retrieve score for a valid student and assessment
    Description: Verify that the API successfully returns the correct score data for a specific student who has completed a specific assessment.
    Priority: High
    Type: Positive

    Given Prepare a GraphQL query for 'getScore'.
    Given Use a valid 'studentId' and 'assessmentId' for an assessment the student has completed.
    Given Include a valid authentication token in the 'Authorization' header.
    Given Send the POST request to the GraphQL endpoint.
    Given Validate the HTTP status code and response body.
    Then The API returns a 200 OK status. The response body's 'data' object contains the 'getScore' field with the correct score information, matching the database record. The response structure and data types are correct.

Scenario: TC_GETSCORE_02: Attempt to retrieve score with an invalid authentication token
    Description: Verify that the API rejects requests made with an invalid or expired authentication token.
    Priority: High
    Type: Negative

    Given Prepare a GraphQL query for 'getScore' with valid student and assessment IDs.
    Given Include an invalid, expired, or malformed token in the 'Authorization' header.
    Given Send the POST request to the GraphQL endpoint.
    Given Observe the HTTP status code and response body.
    Then The API returns a 401 Unauthorized or 403 Forbidden status code. The response body contains an appropriate error message indicating an authentication failure.

Scenario: TC_GETSCORE_03: Request score for a non-existent student
    Description: Verify the API's behavior when a score is requested for a 'studentId' that does not exist in the system.
    Priority: Medium
    Type: Negative

    Given Prepare a GraphQL query for 'getScore'.
    Given Use a 'studentId' that is syntactically valid but does not correspond to any student.
    Given Use a valid 'assessmentId'.
    Given Include a valid authentication token in the header.
    Given Send the POST request to the GraphQL endpoint.
    Then The API returns a 200 OK status. The response body contains an 'errors' array detailing that the student could not be found, or the 'data.getScore' field is null.

Scenario: TC_GETSCORE_04: Request score for a student who has not taken the assessment
    Description: Verify the API's response for a valid student and a valid assessment that the student has not yet started or completed.
    Priority: High
    Type: Negative

    Given Prepare a GraphQL query for 'getScore'.
    Given Use a valid 'studentId'.
    Given Use a valid 'assessmentId' for an assessment that this specific student has no record for.
    Given Include a valid authentication token in the header.
    Given Send the POST request to the GraphQL endpoint.
    Then The API returns a 200 OK status. The 'data.getScore' field in the response is null, indicating no score record was found for that student/assessment combination.

Scenario: TC_GETSCORE_05: Request score for a student with a score of zero
    Description: Verify the API correctly handles and returns a legitimate score of 0, differentiating it from a null (non-existent) score.
    Priority: Medium
    Type: Edge Case

    Given Prepare a GraphQL query for 'getScore'.
    Given Use the 'studentId' and 'assessmentId' for a record where the score is exactly 0.
    Given Include a valid authentication token in the header.
    Given Send the POST request to the GraphQL endpoint.
    Then The API returns a 200 OK status. The response body's 'data.getScore.score' field has a value of 0 (integer or float), not null.

Scenario: TC_GETSCORE_06: Request score using a malformed assessment ID
    Description: Verify that the API handles syntactically invalid input for 'assessmentId' gracefully and returns a validation error.
    Priority: Medium
    Type: Negative

    Given Prepare a GraphQL query for 'getScore'.
    Given Use a valid 'studentId'.
    Given Provide a malformed 'assessmentId' (e.g., contains invalid characters, is too long, or wrong data type).
    Given Include a valid authentication token in the header.
    Given Send the POST request to the GraphQL endpoint.
    Then The API returns a 400 Bad Request status, or a 200 OK with a GraphQL 'errors' array indicating a validation failure for the 'assessmentId' argument.

Scenario: TC_GETSCORE_07: Basic functionality check without providing required arguments
    Description: Verify that the GraphQL schema validation works by sending a query without the required 'studentId' or 'assessmentId' argument.
    Priority: High
    Type: Basic Functionality

    Given Prepare a GraphQL query for 'getScore' but omit the required 'studentId' argument.
    Given Include a valid authentication token in the header.
    Given Send the POST request to the GraphQL endpoint.
    Given Repeat the test, this time omitting the 'assessmentId' argument.
    Then The API returns a 400 Bad Request status or a 200 OK with a GraphQL validation error in the 'errors' array. The error message should clearly state that a required argument is missing.
