# Feature: KAN-3 - Test basic functionality for KAN-3
# Generated by Ultimate Test Automation Coordinator

Feature: Test cases for JIRA ticket KAN-3


Scenario: Test basic functionality for KAN-3
    Description: Basic test case for Test ticket KAN-3
    Priority: Medium

    Given Execute the main functionality
    Given Verify expected behavior
    Then Functionality should work as specified
