# Feature: KAN-1 - Test successful login with valid credentials
# Generated by Ultimate Test Automation Coordinator

Feature: Test cases for JIRA ticket KAN-1


Scenario: Test successful login with valid credentials
    Description: Verify user can login with correct username and password
    Priority: High

    Given Navigate to login page
    Given Enter valid username
    Given Enter valid password
    Given Click login button
    Then User should be logged in and redirected to dashboard

Scenario: Test login failure with invalid password
    Description: Verify system handles incorrect password appropriately
    Priority: High

    Given Navigate to login page
    Given Enter valid username
    Given Enter invalid password
    Given Click login button
    Then Appropriate error message should be displayed
